# Generated by Django 2.2.7 on 2020-01-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('national_identifier', models.BigIntegerField(unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('CEO', 'CEO')], max_length=25)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married')], max_length=25)),
                ('salary', models.PositiveIntegerField()),
                ('deduction', models.PositiveIntegerField(default=0, null=True)),
                ('earning', models.PositiveIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('wife', 'Wife'), ('child', 'Child'), ('husband', 'Husband')], max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Employees')),
            ],
        ),
    ]
