# Generated by Django 2.2.7 on 2020-01-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='activated',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='added',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='deduction_description',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='earning_description',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='freeze',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='job',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='updated',
        ),
    ]
