# Generated by Django 2.2.7 on 2020-01-10 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200109_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationship',
            old_name='employee',
            new_name='employee_id',
        ),
    ]
